### ISSUE TITLE
Building fails during testing

### ISSUE THREAD

**Issue by kmod** [conda-forge/anyio-feedstock#40]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

```
$ conda-smithy rerender
[snip]
$ python3 build-locally.py linux_64_python3.8.____cpython
[snip]
Preparing transaction: ...working... done
Verifying transaction: ...working... done
Executing transaction: ...working... done
export PREFIX=/home/conda/feedstock_root/build_artifacts/anyio_1648512342401/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_
export SRC_DIR=/home/conda/feedstock_root/build_artifacts/anyio_1648512342401/test_tmp
===== testing package: anyio-3.5.0-py38h578d9bd_0 =====
running run_test.py
preflighting uvloop...
... uvloop <module 'uvloop' from '$PREFIX/lib/python3.8/site-packages/uvloop/__init__.py'> _appears_ to be working!
>>> pytest -vv --cov anyio --cov-fail-under 65 --cov-report term-missing:skip-covered --no-cov-on-fail -k not (connection_refused or happy_eyeballs or ipv6 or block_device)
============================= test session starts ==============================
platform linux -- Python 3.8.13, pytest-7.1.1, pluggy-1.0.0 -- $PREFIX/bin/python
cachedir: .pytest_cache
hypothesis profile 'default' -> database=DirectoryBasedExampleDatabase('$SRC_DIR/src/.hypothesis/examples')
rootdir: $SRC_DIR/src, configfile: pyproject.toml, testpaths: tests
plugins: anyio-3.5.0, hypothesis-6.39.6, cov-3.0.0, mock-3.7.0
collecting ... collected 1290 items / 1 error / 142 deselected / 1148 selected
/home/conda/feedstock_root/build_artifacts/anyio_1648512342401/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.8/site-packages/coverage/inorout.py:535: CoverageWarning: Module anyio was previously imported, but not measured (module-not-measured)
  self.warn(msg, slug="module-not-measured")

==================================== ERRORS ====================================
_________________ ERROR collecting tests/test_pytest_plugin.py _________________
ImportError while importing test module '$SRC_DIR/src/tests/test_pytest_plugin.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
../../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.8/site-packages/_pytest/python.py:608: in _importtestmodule
    mod = import_path(self.path, mode=importmode, root=self.config.rootpath)
../../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.8/site-packages/_pytest/pathlib.py:533: in import_path
    importlib.import_module(module_name)
../../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
<frozen importlib._bootstrap>:975: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:671: in _load_unlocked
    ???
../../_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/lib/python3.8/site-packages/_pytest/assertion/rewrite.py:168: in exec_module
    exec(co, module.__dict__)
tests/test_pytest_plugin.py:2: in <module>
    from _pytest.pytester import Testdir
E   ImportError: cannot import name 'Testdir' from '_pytest.pytester' ($PREFIX/lib/python3.8/site-packages/_pytest/pytester.py)
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
======================= 142 deselected, 1 error in 2.16s =======================
Tests failed for anyio-3.5.0-py38h578d9bd_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
WARNING:conda_build.build:Tests failed for anyio-3.5.0-py38h578d9bd_0.tar.bz2 - moving package to /home/conda/feedstock_root/build_artifacts/broken
TESTS FAILED: anyio-3.5.0-py38h578d9bd_0.tar.bz2
Traceback (most recent call last):
  File "/home/kmod/pyston/anyio-feedstock/build-locally.py", line 98, in <module>
    main()
  File "/home/kmod/pyston/anyio-feedstock/build-locally.py", line 92, in main
    run_docker_build(ns)
  File "/home/kmod/pyston/anyio-feedstock/build-locally.py", line 29, in run_docker_build
    subprocess.check_call([script])
  File "/home/kmod/miniconda3/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['.scripts/run_docker_build.sh']' returned non-zero exit status 1.
```

Have you all seen something like this before?

### Installed packages

```shell
n/a
```

### Environment info

```shell
n/a
```

**Comment by bollwyvl** [comment]
> `from _pytest.pytester import Testdir`

Very probably the pytest version has drifted, and that private method changed its name. You could try pinning to a lesser version (very probably `<7`) and it might get further.

**Comment by kmod** [comment]
That worked! Thanks

**Comment by bollwyvl** [comment]
Great! We'll deal with it next time we need to build, please open a new issue if you have other, unrelated issues
